### PR TITLE
adding trained model and adnotations in csv

### PR DESCRIPTION
**Pull request by m-kortas**

### CODE REVIEW

**Comment by majsylw** [comment]
Please remove all binary files from your commit (for example files with pyc extension from __pycache__ directory)

**Review by AgaMiko — CHANGES_REQUESTED** [review]
Hi Magda,
Thanks for you great contribution! Please make a following small changes:
- please remove *.csv files form 
- please remove *.pyc and .DS_Store files
- please move FastRCNNPredictor.ipynb to FastRCNN/notebooks/ beacuse it connected only to the FastRCNN
- please add  README.md and add the info how to generate csv files instead uploading them (e.g. to prepare csv file run the notebooks/json_to_csv.ipynb), and the link to the tutorial you used
Thank you

**Comment by majsylw** [comment]
I think some of above problems can be solved with stligthly changes in ```.gitignore``` file

**Comment by akwasigroch** [comment]
I think, it will be good to merge with sqash option. This is the easiest way to prevent keeping binary files in history.

**Review by AgaMiko — APPROVED** [review]

**Pull request merged**
